services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=/ollama/models
    volumes:
      - ./.models:/ollama/models
      - ./.cache:/root/.cache/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:11434/v1/models >/dev/null || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 30s
